### ISSUE TITLE
Cobalt requires bindings for Interface dependencies that have a default value.

### ISSUE THREAD

**Issue by tbtmuse** [jshannon63/cobalt#17]
Thanks for putting this nice project together!

I have a bit of an issue, most of my classes depend on abstractions and of these, quite a few have a default value, however Cobalt seems to ignore their default value. The call to:

`$dependency = $parameter->getClass();`

returns a value for an interface too and not 'null', Cobalt then immediately stores this as a class dependency without checking if it is an Interface or Abstract class that has a default parameter.

I could created a PR for this check.

**Comment by jshannon63** [comment]
I appreciate your input on this and look forward to your PR.
